import { Bebas_Neue, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const bebas = Bebas_Neue({
  subsets: ["latin"],
  display: 'swap',
  weight: '400',
});

const roboto = Roboto({
  subsets: ["latin"],
  display: 'swap',
  weight: '700',
});

export const metadata = {
  title: "Chalaco Films | Productora Audiovisual",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased bg-white`}>
        {/* Aplicamos la fuente bebas solo al contenedor principal, permitiendo usar roboto en párrafos */}
        <div className={`${bebas.className} flex flex-col min-h-screen relative`}>
          <Navbar />
          <main className="flex-1">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}